project:
  type: website
  output-dir: docs

website:
  title: "Yalemzewod Assefa Gelaw"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - skills.qmd
      - grantsandawards.qmd
      - workshopsandpresentations.qmd
      - publications.qmd
  
    right:
      - icon: twitter
        href: https://twitter.com/yalassefa
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/yalemz
        aria-label: Quarto GitHub
      - icon: linkedin
        href: https://www.linkedin.com/feed/
        aria-label: Quarto LinKedin
      - href: CV/Gelaw_resume_20230804.pdf
        text: cv
  page-footer:
    background: light
    left: 
      - "Copyright 2023, Yalemzewod Gelaw"
    right: 
      - icon: github
        href: https://github.com/yalemzewod
      - icon: twitter
        href: https://twitter.com/yalassefa
  reader-mode: true
  
format:
  html:
    theme: cosmo
    fontsize: 1.16em
    linestretch: 1.7
    css: styles.css
    toc: false
page-layout: full

editor: visual

