project:
  type: website
  preview:
    port: 4200
    browser: true
    

execute:
  freeze: auto

website:
  title: "Yalemzewod Gelaw"
  description: "Personal website of Yalemzewod Gelaw"
  site-url: https://yalemzewodgelaw.com
  rep-url: https://github.com/Yalemzewod/yalemgelaw.github.io
  epo-actions:
    - source
    - issue
  favicon: images/logo.ico
  twitter-card:
    creator: "@yalassefa@
  search: true
  navbar:
    left:
      - href: index.qmd
        text: About
        icon: person-badge-fill
      - href: skills.qmd
        text: Career Summary
        icon: arrow-right-circle-fill
      - href: grantsandawards.qmd
        text: Grants and Awards
        icon: mic-fill
      - href: workshopsandpresentations.qmd
        text: Workshops, training and Presentations
        icon: mic-fill
      - href: publications.qmd
        text: cv
        icon: file-earmark-text-fill
      
    right:
      - icon: twitter
        href: https://twitter.com/yalassefa
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/yalemzewod
        aria-label: Quarto GitHub
      - icon: linkedin
        href: https://www.linkedin.com/feed/
        aria-label: Quarto LinKedin
   
  page-footer:
    background: light
    left: "&#169; 2024 Yalemzewod Gelaw"

    right: 
      - icon: github
        href: https://github.com/yalemzewod
      - icon: twitter
        href: https://twitter.com/yalassefa
  reader-mode: true
  
format:
  html:
    theme: [flatly, assets/styling/theme.scss]
    toc: true
    toc-depth: 4
    pagetitle: "Yalemzewod Gelaw | {{< meta title >}}"
    page-layout: article
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    highlight-style: a11y

