project:
  type: website
  preview:
    port: 4200
    browser: true
    

execute:
  freeze: auto

website:
  title: "Yalemzewod Gelaw"
  description: "Personal website of Yalemzewod Gelaw"
  site-url: https://yalemzewodgelaw.com
  repo-url: https://github.com/Yalemzewod/yalemgelaw.github.io
  repo-actions:
    - source
    - issue
  favicon: images/logo.ico
  twitter-card:
    creator: "@yalassefa"
    
  navbar:
    pinned: true
    logo: images/logo.ico
    left:
      - href: index.qmd
        text: About
        icon: person-badge-fill
      - href: skills.qmd
        text: Career Summary
        icon: arrow-right-circle-fill
      - href: grantsandawards.qmd
        text: Grants and Awards
        icon: mic-fill
      - href: workshopsandpresentations.qmd
        text: Workshops, training and Presentations
        icon: mic-fill
      - href: publications.qmd
        text: Publications
        icon: book-open
      - href: CV/Yalemzewod_Gelaw.pdf
        text: CV
        icon: file-earmark-text-fill
        
      
    right:
      - icon: twitter
        href: https://twitter.com/yalassefa
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/yalemzewod
        aria-label: Quarto GitHub
      - icon: linkedin
        href: https://www.linkedin.com/feed/
        aria-label: Quarto LinKedin

page-footer: 
    background: light
    left: Copyright 2024, Yalemzewod Gelaw
    right: This website is built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/samanthacsik/samanthacsik.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    mainfont: Nunito
    toc: true
