project:
  type: website
  preview:
    port: 4200
    browser: true    

execute:
  freeze: auto

website:
  title: "Yalemzewod A Gelaw"
  description: "Professional blog for practical data manipulation, insightful data visualization, and effective statistical analysis using R and Python"
  site-url: https://yalemzewodgelaw.com
  repo-url: https://github.com/Yalemzewod/yalemgelaw.github.io
  repo-actions:
    - source
    - issue
  favicon: images/logo.png
  twitter-card:
    creator: "@yalassefa"
    
  navbar:
    background: primary
    search: true
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: grantsandawards.qmd
        text: Grants & awards
      - href: workshopsandpresentations.qmd
        text: Workshops & presentations
      - href: publications.qmd
        text: Publications
      - href: tutorials.qmd
        text: Posts
      - href: CV/Yalemzewod_A_Gelaw.pdf
        text: CV

    right:
      - icon: twitter
        href: https://twitter.com/yalassefa
        aria-label: Quarto Twitter
        target: _blank
      - icon: github
        href: https://github.com/yalemzewod
        aria-label: Quarto GitHub
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/feed/
        aria-label: Quarto LinKedin
        target: _blank
      - icon: youtube
        text: YouTube
        href: https://youtube.com/@yz1121?si=y7dpAlVtlEnGRSSm
        target: _blank

page-footer: 
    background: light
    left: "© Copyright 2023, Yalemzewod Gelaw"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    page-layout: full
    sidebar: true
    theme: 
      light: flatly
      dark: darkly
    css: styles.scss
    mainfont: Nunito
    toc: true
    toc-depth: 3
    toc-location: left
