---
title: "Talks and Workshops"
---

## Recent workshops and conference presentations

### Workshop 1

-   Title: [Geostatistical modelling](https://sctravelmedconference.com/speakers-2022/ "Spatial analysis workshop")
-   Date: September 17, 2022
-   Location: Hilton Hotel, Brisbane

I was an invited speaker in the 5th Annual South Cross Travel Medicine Conference and the Inaugural South Cross Tropical Medicine Conference, conducted from 16th - 18th September 2022 at Hilton Hotel Brisbane.



### Workshop 1

-   Title: Introduction to R for data analysis
-   Date: May 25 - August 25, 2024  
-   Location: Virtual

I have provided a five round online training for around 50 PhD students in Australia. 

### Workshop 2

-   Title: [Spatial Analysis Using QGIS and R](https://malariaatlas.org/news/spatial-analysis-training-in-ethiopia-2/ "Spatial analysis in R")
-   Date: December 16 - 20, 2022
-   Location: Nazret, Ethiopia

I provided a five-day workshop on introduction to Spatial analysis in a workshop organized by EPHI National Data Management Centre, in collaboration with MAP and the Australian Based Ethiopian Researchers Network (ABReN), held from October December 16 - 20, 2022.

### Conference Presentation 1

-   Title: [Districts of HIV clustering in Ethiopia: 2015-2017](https://espace.library.uq.edu.au/view/UQ:56e0df8)
-   Date: September 16 - 20, 2019
-   Location: Liverpool, UK

Poster presentation on the 11th European Congress on Tropical Medicine and International Health.

### Conference Presentation 2

-   Title: Epidemiology of tuberculosis and HIV co-infection and its collaborative services towards ending the TB epidemic in Ethiopia ([Abstract no. 1170](https://www.ajtmh.org/view/journals/tpmd/101/5_Suppl/article-p1_a.xml?tab_body=pdf))
-   Date: November 20--24, 2019
-   Location: NATIONAL HARBOR, MARYLAND, USA

Poster presentation on the 68th ASTMH annual conference.

### Conference Presentation 3

-   Title: The Effect of Climate and Altitude Variability on Tuberculosis: A Systematic Review ([Abstract Number: 313](https://ehp.niehs.nih.gov/doi/abs/10.1289/isee.2017.2017-313))
-   Date: September 24 - 28, 2017
-   Location: Sydney, Australia

Oral presentation on the 11th European Congress on the International Society for Environmental Epidemiology (ISEE).
