---
title: "Determinants of late presentation to HIV/AIDS care in Southern Tigray Zone, Northern Ethiopia: an institution based case–control study."
type: "article"
author: "Yalemzewod, Goitom, Akilew, & Kefyalew"
year: "2015"
publication: "AIDS Res Ther"
preprint: ""
doi: "https://doi.org/10.1186/s12981-015-0079-2"
materials: ""
toc: false
categories:
  - Health care seeking
  - HIV/AIDS
  - Late presentation
---

## Citation (Vancouver)

> Gelaw, Y.A., Biks, G.A. & Alene, K.A. Effect of residence on mothers' health care seeking behavior for common childhood illness in Northwest Ethiopia: a community based comparative cross -- sectional study. *BMC Res Notes* **7**, 705 (2014).

## Abstract

### 

Background

Late diagnosis and presentation to human immune deficiency virus (HIV)/acquired immune deficiency syndrome care reduce the benefits of antiretroviral therapy and increase the risk of HIV transmission.

### Objectives

This study was conducted to identify determinants of late presentation to HIV care among people living with HIV in Southern Tigray, Northern Ethiopia.

### Methods

An institution based un-matched case--control (1:2 ratios) supported with qualitative data was conducted in Southern Tigray Zone from March 1 to April 30, 2014. Individuals with HIV enrolled from six randomly selected health facilities were included in the study. Cases were people living with HIV who had cluster of differentiation four count \<350 cells/μl or World Health Organization stages 3 or 4. A total of 442 study participants were included by systematic sampling techniques. Bivariable and multivariable binary logistic regression model was used to identify associated factors. Odds ratio with 95 % CI was computed to assess the strength of the associations.

### Result

Age categories, 25--29 years \[AOR 3, 95 % CI (1.2--8.1)\] and 35--39 years \[AOR 4.1, 95 % CI (1.4--12.5)\], having two \[AOR 6, 95 % CI (1.3--28)\] and more \[AOR 5.2, 95 % CI (1.1--24.8)\] lifetime sexual partners, poor social support \[AOR 2.3, 95 % CI (1.26--4.30)\], second (next to lowest) wealth quintile \[AOR 3.3, 95 % CI 91.3--8.5)\], fear of stigma \[AOR 4.4, 95 % CI (2.2--8.3)\], fear of losing job \[AOR 6.8, 95 % CI (1.8--24.5)\], and reported severe illness \[AOR 4.3, 95 % CI (2.26--8)\] were identified to be the risk factors for late presentation.

### Conclusion

Low socio-economic status and social support, fear of stigma were potential risk factors for late presentation. Efforts towards promoting early care seeking should target on these factors in the study area and other similar settings.
