---
title: "Incidence and risk factors of first-line antiretroviral treatment failure among human immunodeficiency virus-infected children in Amhara regional state, Ethiopia: a retrospective follow-up study."
type: "article"
author: "Maled, Ayele, Yalemzewod, Adino, Kasshun,& Melkitu"
year: "2018"
publication: "BMJ Open"
preprint: ""
doi: "http://dx.doi.org/10.1136/bmjopen-2017-019181"
materials: ""
toc: false
categories:
  - Infectious disease
---

## Citation (Vancouver)

> Sisay MM, Ayele TA, Gelaw YA, Tsegaye AT, Gelaye KA, Melak MF. Incidence and risk factors of first-line antiretroviral treatment failure among human immunodeficiency virus-infected children in Amhara regional state, Ethiopia: a retrospective follow-up study. BMJ open. 2018 Apr 1;8(4):e019181.

## Abstract

**Objective** This study aimed to assess the incidence and risk factors of treatment failure among HIV/AIDS-infected children who were on antiretroviral therapy (ART) in Amhara National Regional State, Ethiopia.

**Methods** A retrospective follow-up study was conducted from January 2010 to March 2016. A total of 824 children under the age of 15 who had started ART were included in the study. Data were collected from children's medical charts and ART registration logbook using a standard checklist. A Weibull regression model was used to identify the risk factors of treatment failure. Adjusted HRs (AHRs) with 95% CIs were used to declare statistical significance.

**Results** The mean (±SD) age of the children was 6.4±3.6 years, with a median (IQR) follow-up of 30.5 (14.6--51.4) months. Sixty-three children (7.7%, 95% CI 5.8 to 9.5) developed treatment failure, 17 (27.0%) of whom were immunological and 46 (73.0%) were clinical failures. The incidence rate of treatment failure was 22.1/10 000 person-months. The cumulative probability of failure was 0.4, with 28 562.5 person-month observations. Lack of disclosure (AHR=4. 4, 95% CI 1.8 to 11.3), opportunistic infections during initiation of ART (AHR=2.3, 95% CI 1.3 to 4.1) and prolonged follow-up (AHR=0.06, 95% CI 0.02 to 0.18) were the main predictors of treatment failure.

**Conclusion** This study revealed that the incidence of treatment failure remains a significant public health concern in Ethiopia. Undisclosed HIV status to children, the presence of opportunistic infections during initiation of ART and prolonged follow-up were found to be the main predictors of treatment failure. Hence, early detection of treatment failure and further studies on viral monitoring need to be considered.
