---
title: "Determinants to antiretroviral treatment non-adherence among adult HIV/AIDS patients in northern Ethiopia."
type: "article"
author: "Berhe, Yigzaw, Melaku, Desalegn, Mebrhatu, & Yalemzewod"
year: "2017"
publication: "AIDS Research and Therapy"
preprint: ""
doi: "https://doi.org/10.1186/s12981-017-0143-1"
materials: ""
toc: false
categories:
  - Infectious disease
---

## Citation (Vancouver)

> Gebrezgabher BB, Kebede Y, Kindie M, Tetemke D, Abay M, Gelaw YA. Determinants to antiretroviral treatment non-adherence among adult HIV/AIDS patients in northern Ethiopia. AIDS research and therapy. 2017 Dec;14(1):1-7.

## Abstract

### Background

Adhering 95% and above of antiretroviral therapy reduces the rate of disease progression and death among people's living human immunodeficiency virus. Though manifold factors have reported as determinant factors of antiretroviral therapy adherence status, perhaps determinants of non-adherence differ up on the activities of patients in the study setting.

### Methods

An institution based unmatched case--control study was conducted in Aksum town. Individuals who had a 6-month follow-up with complete individual information were included in the study. Document review and interviewer based techniques were used to collect the data. Binary logistic regression analysis was used to identify the determinant factors of non-adherence.

### Results

A total of 411 (137 cases and 274 control) study participants were included in the study. The majority of them were male in sex. Having 2 years and above duration on ART \[AOR = 7, 95% CI (2.2, 22.6)\], history of adverse effect \[AOR = 6.9, 95% CI (1.4, 32.9)\], substance use \[AOR = 5.3, 95% CI (1.4, 20.0)\], living with parents \[AOR = 3.4, 95% CI (1.2, 10.3)\], having depression symptom \[AOR = 3.3, 95% CI (1.4, 7.5)\], \<350 cells/mm^3^ cluster of differentiation 4 count \[AOR = 3.2, 95% CI (1.8, 5.8)\] and low dietary diversity \[AOR = 2, 95% CI (1.1, 3.7)\] were found significant determinants of non-adherence to antiretroviral drug.

### Conclusion

Program, social and individual related factors showed a statistically significant associated with non-adherence to antiretroviral therapy. Managing lifestyle by developing self-efficacy of individuals and treating related threat to improve adherence status of antiretroviral therapy is recommended in this study.
