---
title: "Evaluating COVID-19-Related Disruptions to Effective Malaria Case Management in 2020–2021 and Its Potential Effects on Malaria Burden in Sub-Saharan Africa"
type: "article"
author: "Dzianach PA, Rumisha SF,..., Gelaw YA, et al."
year: "2023"
publication: "Tropical Medicine and Infectious Disease"
preprint: ""
doi: "https://doi.org/10.3390/tropicalmed8040216"
materials: ""
toc: false
categories:
  - Geo-spatial
  - Infectious disease
---

## Citation (Vancouver)

> Dzianach PA, Rumisha SF, Lubinda J, Saddler A, van den Berg M, Gelaw YA, Harris JR, Browne AJ, Sanna F, Rozier JA, Galatas B. Evaluating COVID-19-Related Disruptions to Effective Malaria Case Management in 2020--2021 and Its Potential Effects on Malaria Burden in Sub-Saharan Africa. Tropical Medicine and Infectious Disease. 2023 Apr 4;8(4):216.

## Abstract

The COVID-19 pandemic has led to far-reaching disruptions to health systems, including preventative and curative services for malaria. The aim of this study was to estimate the magnitude of disruptions in malaria case management in sub-Saharan Africa and their impact on malaria burden during the COVID-19 pandemic. We used survey data collected by the World Health Organization, in which individual country stakeholders reported on the extent of disruptions to malaria diagnosis and treatment. The relative disruption values were then applied to estimates of antimalarial treatment rates and used as inputs to an established spatiotemporal Bayesian geostatistical framework to generate annual malaria burden estimates with case management disruptions. This enabled an estimation of the additional malaria burden attributable to pandemic-related impacts on treatment rates in 2020 and 2021. Our analysis found that disruptions in access to antimalarial treatment in sub-Saharan Africa likely resulted in approximately 5.9 (4.4--7.2 95% CI) million more malaria cases and 76 (20--132) thousand additional deaths in the 2020--2021 period within the study region, equivalent to approximately 1.2% (0.3--2.1 95% CI) greater clinical incidence of malaria and 8.1% (2.1--14.1 95% CI) greater malaria mortality than expected in the absence of the disruptions to malaria case management. The available evidence suggests that access to antimalarials was disrupted to a significant degree and should be considered an area of focus to avoid further escalations in malaria morbidity and mortality. The results from this analysis were used to estimate cases and deaths in the World Malaria Report 2022 during the pandemic years.
