---
title: "Pertussis outbreak investigation of Mekdela district, south Wollo zone, Amhara region, north-West Ethiopia."
type: "article"
author: "Sefi, Addisu, & Yalemzewod"
year: "2017"
publication: "BMC research notes"
preprint: ""
doi: "https://doi.org/10.1186/s13104-017-2735-1"
materials: ""
toc: false
categories:
  - Child and Adolescent Health
---

## Citation (Vancouver)

> Alamaw SD, Kassa AW, Gelaw YA. Pertussis outbreak investigation of Mekdela district, south Wollo zone, Amhara region, north-West Ethiopia. BMC research notes. 2017 Dec;10:1-7.

## Abstract

### Background

Pertussis is a highly contagious respiratory illness caused by *Bordetella pertussis*. It is one of the most common vaccine-preventable bacterial infections that affects all susceptible individuals, regardless of age. Investigation was done to verify the existence of an outbreak and to identify associated risk factors contributed for the occurrence of an outbreak in Tork and Warkaye villages of Mekdela district.

### Methods

Unmatched community based case control and descriptive cross sectional investigation were conducted with one to two ratios. We used structured questionnaire to collect data from cases and controls.

### Results

A total of 215 cases and eight deaths were identified with an overall attack rate of 1.3 per 1000 population. The mean age of the cases was 3.7 years which was ranged from 3 months to 45 years. The more affected groups were females. On multivariate logistic regression analysis, the risk factor that remained independently statically significant associated with developing pertussis was presence of infected person in the family AOR (adjusted odds ratio): 5.859, (95% CI 2.526--13.589). But previously sick with pertussis AOR: 0.053, (95% CI 0.006--0.460) and receiving full dose of vaccine AOR: 0.256, (95% CI 0.080--0.818) were remained as protective factors from pertussis infection.

### Conclusions

The suspected pertussis outbreak was occurred in remote pocket villages/kebeles of Mekdela district. Routine immunization was not given regularly and functional refrigerators were not available in the health posts. Routine immunization services and treatment of infected patients with appropriate antibiotics should be intensified.
